### ISSUE TITLE
Interface with other electronic structure package

### ISSUE THREAD

**Issue by Jyotirmoyray** [blevine37/pySpawn17#2]
Sir, 
     Can you please tell me how to interface pySpawn to another electronic structure package? Tell me which file to look at.
I really appreciate any help you can provide.

Jyotirmoy Ray

**Comment by sseritan** [comment]
In the `pyspawn.potential` folder, you can see examples of interfaces for the CAS and DFT methods with the TeraChem program (via the the TeraChem Protocol Buffer interface), as well as a test cone potential.

To interface your own ES package, create a new file in that directory that follows the same interface (i.e. defines the required functions specified in comments in other potential files).
To use your potential, be sure to point to your newly defined potential file when initializing your PySpawn run. In the examples, this would be setting the `potential` variable to your file name; for example, [this line in ethylene_sacasscf](https://github.com/blevine37/pySpawn17/blob/86cc957190387589157df815b9b946ef62634f1f/examples/ethylene_sacasscf/start_c2h4.py#L43).
